name: audit-tap
on: [workflow_dispatch]
jobs:
 dry-run:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout
 - name: Selector sanity check
 run: |
 jq -e '.selectors.time_window' audit_capsule.json >/dev/null
 capture:
 needs: dry-run
 runs-on: ubuntu-latest
 steps:
 - name: Scoped capture
 run: |
 python3 tools/audit_tap_stub.py --capsule audit_capsule.json --policy audit_capture_policy.json --inflight inflight_sample.jsonl --out_vault audit_vault/
 attest:
 needs: capture
 runs-on: ubuntu-latest
 steps:
 - name: Sign/attest artifacts
 run: |
 python3 tools/sign.py --in audit_vault --out audit_signed/ --kms key://hypersync/audit
 python3 tools/attest.py --bundle audit_signed/ --out audit_attest.json
