name: persistent-memory
on: [workflow_dispatch]
jobs:
 validate-config:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout
 - name: Validate schema
 run: |
 jq -e . persistent_memory.json >/dev/null
 dry-run-compaction:
 needs: validate-config
 runs-on: ubuntu-latest
 steps:
 - name: Compaction dry run
 run: |
 python3 tools/memory_compactor.py --in data/mem_jsonl --out data/compacted --ttl_ms 604800000 --dry_run
