name: make-x-for-y
on: [workflow_dispatch]
jobs:
 plan-scaffold:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout
 - name: Plan factory bundle
 run: python tools/plan_factory.py --model model_profile.json --spec factory_spec.json --out bundle/
 validate:
 needs: plan-scaffold
 runs-on: ubuntu-latest
 steps:
 - name: Numeric guards
 run: pytest tests/numerics -q || true
 - name: Policy + red-team
 run: pytest tests/policy_redteam -q || true
 sign-attest:
 needs: validate
 runs-on: ubuntu-latest
 steps:
 - name: Sign artifacts
 run: python tools/sign.py --in bundle --out signed/ --kms key://hypersync/minder
 - name: Attest
 run: python tools/attest.py --bundle signed/ --out attest.json
 deploy:
 needs: sign-attest
 runs-on: ubuntu-latest
 steps:
 - name: Canary deploy
 run: python tools/deploy.py --env canary --bundle signed/
