apiVersion: v1
kind: Namespace
metadata:
 name: hypersync

---
apiVersion: v1
kind: ConfigMap
metadata:
 name: hypersync-config
 namespace: hypersync
data:
 config.yaml: |
 mode: hybrid
 federation:
 enabled: true
 protocols:
 - hypersync
 - ipfs
 - libp2p
 replication:
 factor: 3
 strategy: geodesic
 storage:
 cache_levels: 3
 compression: true
 infrastructure:
 gpu: false
 quantum: false
 edge: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: hypersync-database
 namespace: hypersync
spec:
 serviceName: hypersync-database
 replicas: 3
 selector:
 matchLabels:
 app: hypersync-database
 template:
 metadata:
 labels:
 app: hypersync-database
 spec:
 containers:
 - name: database
 image: hypersync/database:latest
 ports:
 - containerPort: 8000
 name: api
 - containerPort: 9000
 name: metrics
 - containerPort: 7000
 name: federation
 env:
 - name: HYPERSYNC_MODE
 value: "hybrid"
 - name: HYPERSYNC_FEDERATION
 value: "true"
 - name: HYPERSYNC_REPLICATION_FACTOR
 value: "3"
 volumeMounts:
 - name: data
 mountPath: /data
 - name: config
 mountPath: /config
 resources:
 requests:
 memory: "2Gi"
 cpu: "1000m"
 limits:
 memory: "4Gi"
 cpu: "2000m"
 livenessProbe:
 httpGet:
 path: /api/v1/database/health
 port: 8000
 initialDelaySeconds: 30
 periodSeconds: 10
 readinessProbe:
 httpGet:
 path: /api/v1/database/health
 port: 8000
 initialDelaySeconds: 10
 periodSeconds: 5
 volumes:
 - name: config
 configMap:
 name: hypersync-config
 volumeClaimTemplates:
 - metadata:
 name: data
 spec:
 accessModes: [ "ReadWriteOnce" ]
 resources:
 requests:
 storage: 100Gi

---
apiVersion: v1
kind: Service
metadata:
 name: hypersync-database
 namespace: hypersync
spec:
 selector:
 app: hypersync-database
 ports:
 - name: api
 port: 8000
 targetPort: 8000
 - name: metrics
 port: 9000
 targetPort: 9000
 - name: federation
 port: 7000
 targetPort: 7000
 clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
 name: hypersync-database-lb
 namespace: hypersync
spec:
 type: LoadBalancer
 selector:
 app: hypersync-database
 ports:
 - name: api
 port: 8000
 targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hypersync-orchestrator
 namespace: hypersync
spec:
 replicas: 2
 selector:
 matchLabels:
 app: hypersync-orchestrator
 template:
 metadata:
 labels:
 app: hypersync-orchestrator
 spec:
 containers:
 - name: orchestrator
 image: hypersync/orchestrator:latest
 ports:
 - containerPort: 8001
 env:
 - name: HYPERSYNC_DB_URL
 value: "http://hypersync-database:8000"
 resources:
 requests:
 memory: "1Gi"
 cpu: "500m"
 limits:
 memory: "2Gi"
 cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
 name: hypersync-orchestrator
 namespace: hypersync
spec:
 selector:
 app: hypersync-orchestrator
 ports:
 - port: 8001
 targetPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hypersync-agents
 namespace: hypersync
spec:
 replicas: 3
 selector:
 matchLabels:
 app: hypersync-agents
 template:
 metadata:
 labels:
 app: hypersync-agents
 spec:
 containers:
 - name: agent-runtime
 image: hypersync/agent-runtime:latest
 ports:
 - containerPort: 8002
 env:
 - name: HYPERSYNC_DB_URL
 value: "http://hypersync-database:8000"
 - name: HYPERSYNC_ORCHESTRATOR_URL
 value: "http://hypersync-orchestrator:8001"
 resources:
 requests:
 memory: "1Gi"
 cpu: "500m"
 limits:
 memory: "2Gi"
 cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
 name: hypersync-agents
 namespace: hypersync
spec:
 selector:
 app: hypersync-agents
 ports:
 - port: 8002
 targetPort: 8002
